# Generated by Django 4.2.2 on 2023-06-13 17:21

import api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone', models.PositiveBigIntegerField(blank=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('location', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastVisit', models.DateField(default=datetime.date(2023, 6, 13))),
                ('totalVisits', models.PositiveSmallIntegerField(default=0)),
                ('storeCredit', models.PositiveIntegerField(default=0)),
                ('customerRating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('customerComment', models.CharField(blank=True, max_length=200, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('price', models.PositiveIntegerField(default=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('totalOrders', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('totalRatings', models.PositiveIntegerField(default=0)),
                ('itemPhoto', models.ImageField(blank=True, upload_to=api.models.MenuUploadTo)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 6, 13, 17, 21, 19, 251158, tzinfo=datetime.timezone.utc))),
                ('tableNumber', models.PositiveSmallIntegerField(default=0)),
                ('tip', models.PositiveSmallIntegerField(default=0)),
                ('orderStatus', models.CharField(blank=True, max_length=10)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('takeawayOrDinein', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('tip', models.PositiveSmallIntegerField(default=0)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='api.customer')),
                ('items', models.ManyToManyField(blank=True, related_name='suborder_items', through='api.ItemDetail', to='api.menuitem')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.order')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('preOrPost', models.SmallIntegerField(default=0)),
                ('licenceNo', models.CharField(blank=True, max_length=15)),
                ('restaurantType', models.CharField(blank=True, max_length=30)),
                ('primColor', models.CharField(blank=True, max_length=10)),
                ('secColor', models.CharField(blank=True, max_length=10)),
                ('logo', models.ImageField(blank=True, upload_to=api.models.restaurantUploadTo)),
                ('owner', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('phone', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('joinDate', models.DateField(default=datetime.datetime(2023, 6, 13, 17, 21, 19, 253956, tzinfo=datetime.timezone.utc))),
                ('customers', models.ManyToManyField(related_name='customers', through='api.CustomerVisit', to='api.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='customerList', through='api.SubOrder', to='api.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='api.menuitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_order', to='api.restaurant'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special', to='api.specialitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='itemType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemtype', to='api.itemtype'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='api.restaurant'),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='api.menuitem'),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='suborder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='suborder', to='api.suborder'),
        ),
        migrations.AddField(
            model_name='customervisit',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.restaurant'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('id', 'restaurant'), name='unique_order'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('restaurant', 'id'), name='unique_menu_item'),
        ),
    ]
