# Generated by Django 4.2.2 on 2023-06-13 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 17, 23, 37, 286522, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='joinDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 17, 23, 37, 289142, tzinfo=datetime.timezone.utc)),
        ),
    ]
