# Generated by Django 4.2.2 on 2023-06-10 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 11, 24, 54, 956621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='joinDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 11, 24, 54, 958417, tzinfo=datetime.timezone.utc)),
        ),
    ]
