# Generated by Django 4.2.2 on 2023-06-09 15:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_phone_alter_menuitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special', to='api.specialitem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='itemType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemtype', to='api.itemtype'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 15, 48, 27, 85854, tzinfo=datetime.timezone.utc)),
        ),
    ]
