# Generated by Django 4.2.2 on 2023-06-10 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_time_alter_restaurant_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderID',
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 11, 42, 37, 862543, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='joinDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 11, 42, 37, 864447, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('id', 'restaurant'), name='unique_order'),
        ),
    ]
