# Generated by Django 4.2.2 on 2023-06-08 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 15, 23, 52, 634592, tzinfo=datetime.timezone.utc)),
        ),
    ]
