# Generated by Django 4.2.2 on 2023-06-13 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_time_alter_restaurant_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 13, 17, 23, 58, 392677, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='joinDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 17, 23, 58, 394319, tzinfo=datetime.timezone.utc)),
        ),
    ]
