# Generated by Django 4.2.3 on 2023-09-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customatizationoptions',
            name='dependencies',
        ),
    ]
