# Generated by Django 4.2.2 on 2023-06-20 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customatizationoptions_dependencies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tables',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='customervisit',
            name='lastVisit',
            field=models.DateField(default=datetime.date(2023, 6, 20)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 13, 41, 29, 754637, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='joinDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 13, 41, 29, 756285, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableNumber', models.PositiveSmallIntegerField(default=0)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('customersSitting', models.ManyToManyField(blank=True, related_name='customer_sitting', to='api.customer')),
                ('restaurant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_table', to='api.restaurant')),
            ],
        ),
    ]
