# Generated by Django 4.2.3 on 2023-09-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customatizationoptions_dependencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(blank=True, choices=[('Awaiting Confirmation', 'NOT_CONFIRMED'), ('Confirmed', 'CONFIRMED'), ('Preparing', 'PREPARING'), ('Dispatching', 'DISPATCHING'), ('Ready', 'READY'), ('Complete', 'COMPLETE')], max_length=30),
        ),
    ]
