# Generated by Django 4.2.2 on 2023-06-20 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restaurant_tables_alter_customervisit_lastvisit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 13, 42, 4, 587239, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='joinDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 13, 42, 4, 588563, tzinfo=datetime.timezone.utc)),
        ),
    ]
