# Generated by Django 4.2.2 on 2023-06-10 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_rating_alter_order_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervisit',
            name='customerComment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customervisit',
            name='customerRating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customervisit',
            name='lastVisit',
            field=models.DateField(default=datetime.date(2023, 6, 10)),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 11, 47, 54, 478414, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='joinDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 10, 11, 47, 54, 481623, tzinfo=datetime.timezone.utc)),
        ),
    ]
