# Generated by Django 4.2.2 on 2023-06-20 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_time_alter_restaurant_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 13, 43, 13, 137113, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='joinDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 13, 43, 13, 138428, tzinfo=datetime.timezone.utc)),
        ),
    ]
