# Generated by Django 4.2.2 on 2023-06-20 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_order_time_alter_restaurant_joindate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tables',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 13, 48, 23, 127235, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='joinDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 20, 13, 48, 23, 128573, tzinfo=datetime.timezone.utc)),
        ),
    ]
