# Generated by Django 4.2.3 on 2023-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_itemdetail_price_quantity_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='acceptingOrders',
            field=models.BooleanField(default=True),
        ),
    ]
