# Generated by Django 4.2.3 on 2023-09-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_restaurant_acceptingorders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'managed': True, 'ordering': ['name']},
        ),
    ]
