# Generated by Django 4.2.3 on 2023-09-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_restaurant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name']},
        ),
    ]
