# Generated by Django 4.2.3 on 2023-10-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
