# Generated by Django 4.2.3 on 2023-10-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_menuitem_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customervisit',
            name='customerComment',
        ),
        migrations.RemoveField(
            model_name='customervisit',
            name='customerRating',
        ),
        migrations.RemoveField(
            model_name='customervisit',
            name='storeCredit',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='totalOrders',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tableNumber',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='preOrPost',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='primColor',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='secColor',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tables',
        ),
        migrations.RemoveField(
            model_name='suborder',
            name='tip',
        ),
        migrations.AlterField(
            model_name='menuitemcustomization',
            name='customizationType',
            field=models.CharField(blank=True, choices=[('radio', 'Can select only one'), ('checkbox', 'Can select many')], default='radio', max_length=10),
        ),
    ]
