# Generated by Django 4.2.3 on 2023-10-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_customervisit_customercomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='totalRatings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
