# Generated by Django 4.2.3 on 2023-10-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_restaurant_rating_restaurant_totalratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='dietaryType',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('EGG', 'Egg')], default='VEG', max_length=10),
        ),
    ]
