# Generated by Django 4.2.3 on 2023-10-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_menuitem_dietarytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='itemType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itemtype', to='api.itemtype'),
            preserve_default=False,
        ),
    ]
