# Generated by Django 4.2.3 on 2023-10-16 05:43

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_menuitem_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='Currently Available'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='dietaryType',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('EGG', 'Egg')], default='VEG', max_length=10, verbose_name='Food Type'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='itemPhoto',
            field=models.ImageField(blank=True, upload_to=api.models.MenuUploadTo, verbose_name='Item Photo'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='itemType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemtype', to='api.itemtype', verbose_name='Item Type'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.PositiveIntegerField(default=100, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='totalRatings',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Ratings'),
        ),
    ]
