# Generated by Django 4.2.7 on 2023-11-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_menuitem_isactive_alter_menuitem_dietarytype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='isActive',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=True, verbose_name='Currently Available'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='acceptingOrders',
            field=models.BooleanField(choices=[('True', 'Yes'), ('False', 'No')], default=True),
        ),
    ]
