# Generated by Django 4.2.7 on 2023-12-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_menuitem_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(choices=[('PAID', 'Paid'), ('NOT_PAID', 'Not Paid'), ('REFUNDED', 'Refunded')], default='NOT_PAID', max_length=15),
        ),
    ]
