# Generated by Django 4.2.7 on 2023-12-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_order_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentStatus',
            field=models.CharField(choices=[('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('PENDING', 'Pending')], default='PENDING', max_length=15),
        ),
    ]
