# Generated by Django 4.2.7 on 2023-12-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_order_orderstatus_alter_order_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='isActive',
            field=models.BooleanField(choices=[(True, 'Available'), (False, 'Not Available')], default=True, verbose_name='Currently Available'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='acceptingOrders',
            field=models.BooleanField(choices=[(True, 'Accepting Orders'), (False, 'Not Accepting Orders')], default=True),
        ),
    ]
