# Generated by Django 5.0.1 on 2024-02-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_menuitem_isactive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='licenceNo',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
    ]
