# Generated by Django 4.2.7 on 2023-11-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTPAuth', '0002_alter_analytics_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analytics',
            name='referrer',
        ),
    ]
