# Generated by Django 4.2.7 on 2023-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTPAuth', '0003_remove_analytics_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='host',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='remote_addr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='user_agent',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
