# Generated by Django 4.2.7 on 2023-12-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='terminal_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentstatus',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
