# Generated by Django 4.2.7 on 2023-12-03 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_paymentstatus_terminal_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
