# Generated by Django 4.2.7 on 2023-12-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_paymentstatus_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'ordering': ['-order__id', '-time']},
        ),
    ]
