# Generated by Django 4.2.7 on 2024-01-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Payments", "0004_alter_paymentstatus_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentstatus",
            name="payment_gateway",
            field=models.CharField(
                choices=[("PhonePe", "Phone Pe"), ("RazorPay", "Rzp")], max_length=50
            ),
        ),
    ]
