# Generated by Django 5.0.1 on 2024-02-17 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0004_alter_paymentstatus_options'),
        ('api', '0025_remove_restaurant_licenceno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentstatus',
            name='payment_gateway',
            field=models.CharField(choices=[('PhonePe', 'Phone Pe'), ('RazorPay', 'Rzp')], max_length=50),
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('account_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_details', to='api.restaurant')),
            ],
        ),
    ]
